services:
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    restart : always
    ports:
      - "3396:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_DUMP_DIR}/init.sql:/docker-entrypoint-initdb.d/autopro.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MY_DATABASE}
    networks:
      - backend

  apiprojet:
    image: ${API_IMAGE_NAME}
    container_name: apiprojet
    restart: on-failure
    ports:
      - "9000:8082"
    depends_on:
      - mysql_server
    networks:
      - backend

  webspringboot:
    image: ${WEB_IMAGE_NAME}
    container_name: webspringboot
    ports:
      - "9091:8081"
    depends_on:
      - apiprojet
    healthcheck:
      test: curl -f http://apiprojet:9000/personnes || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    networks:
      - backend

networks:
  backend:
